# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "video=2880x1800@60" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a33aa93f-df9c-4961-bef4-071fc56e7e79";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fef781a1-6b93-491e-89f0-1b9ad23e3eea"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
