{ pkgs, ... }:
{
    environment.systemPackages = with pkgs; [
        neovim
        ffmpeg
        gh
        ripgrep
        fd
        go
        python3
        ruff
        nil
        cargo
        rustc
        docker
        docker-compose
        colima
        stow
        skimpdf
        uv
        vscode
        bat
        tldr
        btop
        jankyborders
        shortcat
        rust-analyzer
        yt-dlp
        cmake
        google-chrome
        opencode
        claude-code
        utm
    ];
}
