#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

yabai -m config top_padding 5
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20

# Auto balance makes it so all windows always occupy the same space, independent of how deeply nested they are in the window tree.
# When a new window is inserted or a window is removed, the split ratios will be automatically adjusted.
yabai -m config auto_balance off

# If auto balance is disabled, the split ratio defines how much space each window occupies after a new split is created.
yabai -m config split_ratio 0.5

# set mouse interaction modifier key
yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
# yabai -m rule --add app="^(Discord)$" opacity=0.95
yabai -m rule --add app="^(Messages|Finder|Notion|Activity Monitor|Raycast|Discord)$" opacity=0.85
# yabai -m config normal_window_opacity 0.9

# Auto-focus first window when switching spaces
# yabai -m signal --add event=space_changed action="yabai -m window --focus first || yabai -m window --focus last"

yabai -m signal --add event=window_destroyed action="yabai -m window --focus recent 2>/dev/null || yabai -m window --focus first 2>/dev/null"

yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|App Store)$" manage=off

# borders active_color=0xff8f9591 inactive_color=0xff31363c width=5.0 &
borders active_color=0xffd8d3b7 inactive_color=0xff4b5568 width=5.0 &

